/**
 * Config files and copy-paste snippets. The file shape is what `normalizeConfig` reads back,
 * so `normalizeConfig(toConfigFile(cfg)).config` equals `cfg` in both modes.
 */

import { getDefaults } from './defaults';
import { getPresetConfig } from './normalize';
import { diffConfigs, getLeafPaths, getPath, setPath } from './paths';
import type { PresetId } from './presets';
import { CONFIG_VERSION, type PixelLifeConfig, type PixelLifeConfigInput } from './schema';

/** Where exported files point their `$schema` by default (JSON Schema generated by `npm run schema`). */
export const DEFAULT_SCHEMA_URL = './pixel-life.schema.json';

export type PixelLifeConfigFile = {
  $schema: string;
  version: typeof CONFIG_VERSION;
} & PixelLifeConfigInput;

export interface ToConfigFileOptions {
  /** 'full' writes every parameter, 'diff' only those differing from `base`. Default 'full'. */
  mode?: 'full' | 'diff';
  /** Base for 'diff'. A preset base adds `extends`. Default 'defaults'. */
  base?: 'defaults' | PresetId;
  schemaUrl?: string;
}

export function toConfigFile(
  cfg: PixelLifeConfig,
  opts: ToConfigFileOptions = {},
): PixelLifeConfigFile {
  const { mode = 'full', base = 'defaults', schemaUrl = DEFAULT_SCHEMA_URL } = opts;
  const head = { $schema: schemaUrl, version: CONFIG_VERSION };
  let body: Record<string, unknown> = {};
  if (mode === 'full') {
    // Rebuild in schema order (never trust the key order of the incoming object).
    for (const p of getLeafPaths()) body = setPath(body, p, structuredCopy(getPath(cfg, p)));
    return { ...head, ...body } as PixelLifeConfigFile;
  }
  const baseCfg = base === 'defaults' ? getDefaults() : getPresetConfig(base);
  for (const p of diffConfigs(baseCfg, cfg))
    body = setPath(body, p, structuredCopy(getPath(cfg, p)));
  const ext = base === 'defaults' ? {} : { extends: base };
  return { ...head, ...ext, ...body } as PixelLifeConfigFile;
}

function structuredCopy(v: unknown): unknown {
  return Array.isArray(v) ? v.slice() : v;
}

// ---------------------------------------------------------------------------------------------
// Snippets

const IDENT = /^[A-Za-z_$][\w$]*$/;

function jsString(s: string): string {
  return `'${s.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
}

function jsNumber(n: number): string {
  // Trim float noise (0.30000000000000004) without changing meaningful precision.
  return String(Number.isFinite(n) ? Number.parseFloat(n.toPrecision(12)) : 0);
}

/** Formats plain data as a JS object literal: unquoted keys, single quotes, short arrays inline. */
export function toJsLiteral(v: unknown, indent = 0, width = 100): string {
  const pad = '  '.repeat(indent);
  const inner = '  '.repeat(indent + 1);
  if (v === null || v === undefined) return 'undefined';
  if (typeof v === 'string') return jsString(v);
  if (typeof v === 'number') return jsNumber(v);
  if (typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    const items = v.map((x) => toJsLiteral(x, indent + 1, width));
    const flat = `[${items.join(', ')}]`;
    if (flat.length + indent * 2 <= width - 20 && !flat.includes('\n')) return flat;
    return `[\n${items.map((x) => `${inner}${x},`).join('\n')}\n${pad}]`;
  }
  if (typeof v === 'object') {
    const entries = Object.entries(v as Record<string, unknown>).filter(([, x]) => x !== undefined);
    if (entries.length === 0) return '{}';
    const lines = entries.map(
      ([k, x]) =>
        `${inner}${IDENT.test(k) ? k : jsString(k)}: ${toJsLiteral(x, indent + 1, width)},`,
    );
    return `{\n${lines.join('\n')}\n${pad}}`;
  }
  return 'undefined';
}

/** Code snippets carry the config without `$schema` (it only helps editors with JSON files). */
function codeBody(file: PixelLifeConfigInput): Record<string, unknown> {
  const { $schema: _omit, ...rest } = file;
  return rest;
}

export function toJsonSnippet(file: PixelLifeConfigInput): string {
  return `${JSON.stringify(file, null, 2)}\n`;
}

export function toTsSnippet(file: PixelLifeConfigInput): string {
  return [
    "import type { PixelLifeConfigInput } from 'pixel-life';",
    '',
    `export const pixelLifeConfig = ${toJsLiteral(codeBody(file))} satisfies PixelLifeConfigInput;`,
    '',
  ].join('\n');
}

export function toReactSnippet(file: PixelLifeConfigInput): string {
  return [
    "import type { PixelLifeConfigInput } from 'pixel-life';",
    "import { PixelLife } from 'pixel-life/react';",
    '',
    `const pixelLifeConfig = ${toJsLiteral(codeBody(file))} satisfies PixelLifeConfigInput;`,
    '',
    'export function Background() {',
    '  return <PixelLife config={pixelLifeConfig} />;',
    '}',
    '',
  ].join('\n');
}

export function toHtmlSnippet(file: PixelLifeConfigInput): string {
  return [
    '<pixel-life id="bg"></pixel-life>',
    '<script type="module">',
    "  import 'pixel-life/element/define';",
    `  document.getElementById('bg').config = ${toJsLiteral(codeBody(file), 1)};`,
    '</script>',
    '',
  ].join('\n');
}
