/**
 * THE config schema tree. Everything else (types, defaults, normalization, stand UI, JSON Schema,
 * GPU layout) is derived from this object, so paths, ranges and defaults live only here.
 *
 * Defaults are the "reference" look. Units: "cells" = grid pitch units; "mode units" =
 * aspect-correct space where 1.0 = half of the host's shorter side.
 */

import {
  angle,
  bool,
  color,
  type DeepPartial,
  enumField,
  group,
  type InferConfig,
  int,
  type NodeAt,
  num,
  type PathValue,
  palette,
  type SchemaLeafPaths,
  vec2,
} from './fields';
import type { PresetId } from './presets';

const grid = group(
  {
    label: 'Grid',
    order: 10,
    description: 'Size and shape of the pixel-grid cells.',
  },
  {
    sizing: enumField({
      values: ['pitch', 'count'] as const,
      default: 'count',
      label: 'Cell sizing',
      description:
        'Size the grid by a fixed pitch in pixels or by the number of cells along the shorter side of the container.',
      labels: { pitch: 'Pitch in px', count: 'Cell count' },
      live: 'realloc',
    }),
    pitch: num({
      min: 4,
      max: 96,
      step: 1,
      unit: 'px',
      default: 24,
      label: 'Pitch',
      description: 'Distance between the centers of neighboring cells, in CSS pixels.',
      live: 'realloc',
      visibleWhen: { path: 'grid.sizing', eq: 'pitch' },
    }),
    count: int({
      min: 8,
      max: 200,
      step: 1,
      default: 31,
      label: 'Cells',
      description:
        'How many cells fit along the shorter side of the container, so the composition looks the same in a square, a banner or full screen.',
      live: 'realloc',
      visibleWhen: { path: 'grid.sizing', eq: 'count' },
    }),
    gap: num({
      min: 0.02,
      max: 0.6,
      step: 0.01,
      default: 0.27,
      label: 'Gap',
      description: 'Fraction of the pitch taken by the dark gap between cells.',
      gpu: true,
    }),
    roundness: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.3,
      label: 'Roundness',
      description: 'Corner radius as a fraction of half a cell: 0 is a square, 1 is a circle.',
      gpu: true,
    }),
    softness: num({
      min: 0,
      max: 3,
      step: 0.05,
      unit: 'px',
      default: 0.6,
      label: 'Edge softness',
      description: 'Feathering of the cell edge, in device pixels.',
      gpu: true,
    }),
    emitter: num({
      min: 0,
      max: 0.6,
      step: 0.01,
      default: 0.18,
      label: 'Emitter',
      description: 'How much brighter the center of a cell is than its edges.',
      gpu: true,
    }),
    bevel: num({
      min: 0,
      max: 0.15,
      step: 0.01,
      default: 0,
      label: 'Bevel',
      description: 'Subtle depth: a light top edge and a dark bottom edge on each cell.',
      gpu: true,
      advanced: true,
    }),
  },
);

const scene = group(
  {
    label: 'Composition',
    order: 20,
    description: 'Position and scale of the whole picture inside the container.',
  },
  {
    center: vec2({
      min: -1,
      max: 1,
      step: 0.01,
      default: [-0.02, -0.02],
      label: 'Center',
      description: 'Composition center in mode units (1 = half of the shorter side).',
      gpu: true,
    }),
    zoom: num({
      min: 0.25,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Zoom',
      description: 'Magnifies all modes around the center.',
      gpu: true,
    }),
  },
);

const animation = group(
  {
    label: 'Animation',
    order: 30,
    description: 'Global speed, mode blending and cell liveliness.',
  },
  {
    speed: num({
      min: 0,
      max: 4,
      step: 0.01,
      default: 1,
      label: 'Speed',
      description: 'Global time multiplier for all modes.',
    }),
    blend: enumField({
      values: ['screen', 'add', 'max'] as const,
      default: 'screen',
      label: 'Mode blending',
      description: 'How several active modes are combined.',
      labels: { screen: 'Screen', add: 'Add', max: 'Max' },
      gpu: true,
    }),
    brightness: num({
      min: 0,
      max: 3,
      step: 0.01,
      default: 1,
      label: 'Brightness',
      description: 'Cell intensity multiplier.',
      gpu: true,
    }),
    gamma: num({
      min: 0.3,
      max: 3,
      step: 0.01,
      default: 1.15,
      label: 'Contrast (gamma)',
      description: 'Values above 1 darken the midtones and increase contrast.',
      gpu: true,
    }),
    floor: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.16,
      label: 'Unlit visibility',
      description: 'How visible the unlit cells are.',
      gpu: true,
    }),
    energy: num({
      min: 0,
      max: 3,
      step: 0.01,
      default: 1,
      label: 'Energy',
      description: 'External drive: handy for modulating with audio or events.',
      gpu: true,
    }),
    flicker: group(
      { label: 'Flicker', description: 'Slow random brightness breathing of each cell.' },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.4,
          label: 'Amount',
          description: 'Flicker amplitude.',
          gpu: true,
        }),
        rate: num({
          min: 0.05,
          max: 5,
          step: 0.01,
          unit: 'Hz',
          default: 0.3,
          label: 'Rate',
          description: 'How fast the brightness changes.',
          gpu: true,
        }),
      },
    ),
    sparkle: group(
      { label: 'Sparkle', description: 'Rare short flashes of individual cells.' },
      {
        amount: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.35,
          label: 'Amount',
          description: 'Brightness added during a flash.',
          gpu: true,
        }),
        rate: num({
          min: 0,
          max: 0.05,
          step: 0.001,
          default: 0.008,
          label: 'Rate',
          description: 'Flash probability per cell per second.',
          gpu: true,
        }),
        duration: num({
          min: 0.1,
          max: 2,
          step: 0.01,
          unit: 's',
          default: 0.5,
          label: 'Duration',
          description: 'Length of a single flash.',
          gpu: true,
        }),
      },
    ),
    sparsity: group(
      {
        label: 'Sparsity',
        description: 'On the outskirts cells switch off entirely instead of dimming.',
      },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.55,
          label: 'Amount',
          description: 'Share of switched-off cells in weak areas.',
          gpu: true,
        }),
        period: num({
          min: 0.5,
          max: 10,
          step: 0.1,
          unit: 's',
          default: 3,
          label: 'Period',
          description: 'How often the switched-off cells are reshuffled.',
          gpu: true,
        }),
      },
    ),
  },
);

const weight = (value: number, label = 'Weight') =>
  num({
    min: 0,
    max: 1,
    step: 0.01,
    default: value,
    label,
    description: 'Contribution of the mode to the final image; 0 turns the mode off.',
    gpu: true,
  });

const modes = group(
  {
    label: 'Animation modes',
    order: 40,
    description: 'Layers of the brightness field; several modes can be mixed at once.',
  },
  {
    flow: group(
      { label: 'Flow', kind: 'mode', description: 'A smoothly flowing noise pattern.' },
      {
        weight: weight(0.1),
        scale: num({
          min: 0.2,
          max: 8,
          step: 0.01,
          scale: 'log',
          default: 1.6,
          label: 'Scale',
          description: 'Noise frequency: higher values give smaller blobs.',
          gpu: true,
        }),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.25,
          label: 'Speed',
          description: 'How fast the pattern flows.',
        }),
        direction: angle({
          default: 30,
          label: 'Direction',
          description: 'Where the pattern flows.',
          gpu: true,
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.45,
          label: 'Threshold',
          description: 'Higher values leave fewer glowing blobs.',
          gpu: true,
        }),
        softness: num({
          min: 0.02,
          max: 1,
          step: 0.01,
          default: 0.3,
          label: 'Softness',
          description: 'Width of the transition from dark to light.',
          gpu: true,
        }),
      },
    ),
    sphere: group(
      {
        label: 'Sphere',
        kind: 'mode',
        description: 'A glowing hollow orb with a rim and a soft fade.',
      },
      {
        weight: weight(1),
        radius: num({
          min: 0.1,
          max: 1.6,
          step: 0.01,
          default: 0.68,
          label: 'Radius',
          description: 'Sphere radius in mode units.',
          gpu: true,
        }),
        shift: vec2({
          min: -1,
          max: 1,
          step: 0.01,
          default: [0.02, 0.16],
          label: 'Shell offset',
          description:
            'Offset of the glowing shell relative to the hole: the ring is thicker and denser on that side while the hole stays centered.',
          gpu: true,
        }),
        hole: num({
          min: 0,
          max: 0.9,
          step: 0.01,
          default: 0.25,
          label: 'Hole',
          description: 'Radius of the dark middle; 0 gives a solid orb.',
          gpu: true,
        }),
        holeSoftness: num({
          min: 0.01,
          max: 0.5,
          step: 0.01,
          default: 0.12,
          label: 'Hole softness',
          description: 'Width of the transition from the hole to the bright ring.',
          gpu: true,
        }),
        rimPower: num({
          min: 0.3,
          max: 6,
          step: 0.01,
          default: 1.3,
          label: 'Rim',
          description: 'Higher values push the light toward the edge of the sphere.',
          gpu: true,
        }),
        outerFalloff: num({
          min: 0.05,
          max: 1.5,
          step: 0.01,
          default: 0.38,
          label: 'Outer falloff',
          description: 'How far the light reaches beyond the sphere radius.',
          gpu: true,
        }),
        lightAngle: angle({
          default: 200,
          label: 'Light direction',
          description: 'Which side of the sphere is lit more strongly.',
          gpu: true,
        }),
        lightStrength: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.45,
          label: 'Light strength',
          description: 'Contrast between the lit side and the shadow side.',
          gpu: true,
        }),
        rotationSpeed: num({
          min: -2,
          max: 2,
          step: 0.01,
          default: 0.12,
          label: 'Rotation',
          description: 'Rotation speed of the sphere surface (the sign sets the direction).',
        }),
        tilt: angle({
          min: -60,
          max: 60,
          default: 20,
          label: 'Axis tilt',
          description: 'Tilt of the rotation axis.',
          gpu: true,
        }),
        surface: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.55,
          label: 'Surface',
          description: 'Strength of the pattern on the sphere surface.',
          gpu: true,
        }),
        surfaceScale: num({
          min: 0.5,
          max: 8,
          step: 0.01,
          default: 2.5,
          label: 'Surface scale',
          description: 'Frequency of the surface pattern.',
          gpu: true,
        }),
        wobble: num({
          min: 0,
          max: 0.3,
          step: 0.005,
          default: 0.08,
          label: 'Wobble',
          description: 'Noise distortion of the sphere outline.',
          gpu: true,
        }),
        breathe: num({
          min: 0,
          max: 0.2,
          step: 0.005,
          default: 0.025,
          label: 'Breathing',
          description: 'Amplitude of the radius pulsation.',
          gpu: true,
        }),
        breatheSpeed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.35,
          label: 'Breathing rate',
          description: 'Frequency of the radius pulsation.',
        }),
        fadeAngle: angle({
          default: 345,
          label: 'Fade side',
          description: 'Direction in which the sphere dissolves into the background.',
          gpu: true,
        }),
        fadeAmount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 1,
          label: 'Fade amount',
          description: 'How strongly the fade side dims.',
          gpu: true,
        }),
      },
    ),
    pulse: group(
      { label: 'Pulse', kind: 'mode', description: 'Concentric rings spreading from the center.' },
      {
        weight: weight(0),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.45,
          label: 'Speed',
          description: 'How fast the rings expand.',
        }),
        frequency: num({
          min: 0.5,
          max: 12,
          step: 0.01,
          default: 3,
          label: 'Frequency',
          description: 'Rings per mode unit.',
          gpu: true,
        }),
        width: num({
          min: 0.02,
          max: 0.6,
          step: 0.01,
          default: 0.14,
          label: 'Width',
          description: 'Ring thickness.',
          gpu: true,
        }),
        breathe: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Breathing',
          description: 'Overall brightness pulsation.',
          gpu: true,
        }),
        falloff: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 1,
          label: 'Falloff',
          description: 'How fast the rings fade with distance.',
          gpu: true,
        }),
        origin: vec2({
          min: -1,
          max: 1,
          step: 0.01,
          default: [0, 0],
          label: 'Origin',
          description: 'Ring center relative to the composition center.',
          gpu: true,
        }),
      },
    ),
    wave: group(
      { label: 'Waves', kind: 'mode', description: 'Traveling plane waves with interference.' },
      {
        weight: weight(0),
        angle: angle({
          default: 20,
          label: 'Direction',
          description: 'Direction in which the waves travel.',
          gpu: true,
        }),
        frequency: num({
          min: 0.2,
          max: 12,
          step: 0.01,
          default: 2.5,
          label: 'Frequency',
          description: 'Crests per mode unit.',
          gpu: true,
        }),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.5,
          label: 'Speed',
          description: 'How fast the waves travel.',
        }),
        sharpness: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Sharpness',
          description: 'Higher values give narrow bright crests.',
          gpu: true,
        }),
        interference: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.5,
          label: 'Interference',
          description: 'Mix of a second wave at a different angle.',
          gpu: true,
        }),
      },
    ),
    ripple: group(
      { label: 'Ripples', kind: 'mode', description: 'Random rings, like drops falling on water.' },
      {
        weight: weight(0),
        rate: num({
          min: 0,
          max: 6,
          step: 0.01,
          unit: '/s',
          default: 1.2,
          label: 'Rate',
          description: 'How many drops appear per second.',
          gpu: true,
        }),
        speed: num({
          min: 0.05,
          max: 2,
          step: 0.01,
          default: 0.4,
          label: 'Speed',
          description: 'How fast a ring expands.',
          gpu: true,
        }),
        width: num({
          min: 0.02,
          max: 0.4,
          step: 0.01,
          default: 0.09,
          label: 'Width',
          description: 'Ring thickness.',
          gpu: true,
        }),
        life: num({
          min: 0.5,
          max: 6,
          step: 0.1,
          unit: 's',
          default: 2.5,
          label: 'Lifetime',
          description: 'How long a single ring lives.',
          gpu: true,
        }),
      },
    ),
    vortex: group(
      { label: 'Vortex', kind: 'mode', description: 'Twisted spiral arms.' },
      {
        weight: weight(0),
        arms: int({
          min: 1,
          max: 8,
          step: 1,
          default: 3,
          label: 'Arms',
          description: 'Number of spiral arms.',
          gpu: true,
        }),
        twist: num({
          min: -10,
          max: 10,
          step: 0.1,
          default: 3,
          label: 'Twist',
          description: 'How tightly the arms are wound (the sign sets the direction).',
          gpu: true,
        }),
        speed: num({
          min: -3,
          max: 3,
          step: 0.01,
          default: 0.3,
          label: 'Speed',
          description: 'Rotation speed of the vortex.',
        }),
        falloff: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.9,
          label: 'Falloff',
          description: 'How fast the vortex fades away from the center.',
          gpu: true,
        }),
        sharpness: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.4,
          label: 'Sharpness',
          description: 'Crispness of the arm edges.',
          gpu: true,
        }),
      },
    ),
    life: group(
      {
        label: 'Life',
        kind: 'mode',
        description: "A cellular automaton in the spirit of Conway's Game of Life.",
      },
      {
        weight: weight(0),
        stepRate: num({
          min: 1,
          max: 30,
          step: 0.1,
          unit: 'Hz',
          default: 8,
          label: 'Steps per second',
          description: 'Evolution speed of the automaton.',
        }),
        birthRate: num({
          min: 0,
          max: 0.05,
          step: 0.0005,
          default: 0.004,
          label: 'Spontaneous births',
          description: 'Chance of a random cell birth per step; keeps the field from dying out.',
        }),
        fadeSteps: int({
          min: 1,
          max: 16,
          step: 1,
          default: 4,
          label: 'Fade',
          description: 'How many steps a dead cell takes to fade out.',
          gpu: true,
        }),
        seedDensity: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.3,
          label: 'Seed density',
          description: 'Share of live cells after a reset.',
        }),
        rule: enumField({
          values: ['conway', 'highlife', 'daynight', 'seeds'] as const,
          default: 'conway',
          label: 'Rule',
          description: 'Birth and survival rule; changing it restarts the field.',
          labels: {
            conway: 'Conway B3/S23',
            highlife: 'HighLife B36/S23',
            daynight: 'Day & Night',
            seeds: 'Seeds B2/S',
          },
          live: 'restart',
        }),
      },
    ),
    rain: group(
      { label: 'Rain', kind: 'mode', description: 'Falling glowing drops with a trail.' },
      {
        weight: weight(0),
        speed: num({
          min: 0.1,
          max: 5,
          step: 0.01,
          default: 1,
          label: 'Speed',
          description: 'How fast the drops fall.',
        }),
        density: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.25,
          label: 'Density',
          description: 'Share of columns with rain.',
          gpu: true,
        }),
        tail: num({
          min: 0.05,
          max: 1.5,
          step: 0.01,
          default: 0.5,
          label: 'Trail',
          description: 'Length of the glowing trail behind a drop.',
          gpu: true,
        }),
        angle: angle({
          min: -45,
          max: 45,
          default: 0,
          label: 'Slant',
          description: 'Deviation of the rain from vertical.',
          gpu: true,
        }),
      },
    ),
  },
);

const colorGroup = group(
  {
    label: 'Color',
    order: 50,
    description: 'The palette and how it is laid over the grid.',
  },
  {
    palette: palette({
      default: [
        '#a0206a',
        '#f21239',
        '#e0267a',
        '#5a44d0',
        '#2a55e0',
        '#1f5fe8',
        '#0870f8',
        '#0476ff',
        '#0a84f2',
        '#0a8cf0',
        '#0a78e8',
        '#0b5ccc',
      ],
      minStops: 1,
      maxStops: 32,
      label: 'Palette',
      description: 'Gradient color stops, from start to end.',
    }),
    interpolation: enumField({
      values: ['oklab', 'linear', 'steps'] as const,
      default: 'oklab',
      label: 'Interpolation',
      description: 'How neighboring palette colors are blended.',
      labels: { oklab: 'OKLab (smooth)', linear: 'Linear (RGB)', steps: 'Steps' },
      live: 'lut',
    }),
    mapping: enumField({
      values: ['spatial', 'radial', 'angular', 'intensity', 'noise'] as const,
      default: 'spatial',
      label: 'Mapping',
      description: 'What sets the position of a cell on the palette.',
      labels: {
        spatial: 'Along axis',
        radial: 'Radial',
        angular: 'Angular',
        intensity: 'By brightness',
        noise: 'Noise',
      },
      transition: 'crossfade',
      gpu: true,
    }),
    angle: angle({
      default: 22,
      label: 'Axis angle',
      description: 'Direction from the start of the palette to its end (axis mapping).',
      gpu: true,
    }),
    bend: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0.35,
      label: 'Axis bend',
      description:
        'Bends the color boundaries into arcs around the center (axis mapping): the start color gathers into a crescent on one side.',
      gpu: true,
    }),
    scale: num({
      min: 0.1,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Stretch',
      description: 'Higher values repeat the palette more often.',
      gpu: true,
    }),
    offset: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0,
      label: 'Offset',
      description: 'Shifts the palette along the mapping.',
      gpu: true,
    }),
    warp: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Warp',
      description: 'Noise distortion of the color boundaries.',
      gpu: true,
    }),
    warpScale: num({
      min: 0.2,
      max: 6,
      step: 0.01,
      default: 1.3,
      label: 'Warp scale',
      description: 'Frequency of the warp noise.',
      gpu: true,
    }),
    jitter: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.12,
      label: 'Jitter',
      description: 'Random color offset of each cell.',
      gpu: true,
    }),
    intensityShift: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Brightness shift',
      description: 'Bright cells move along the palette.',
      gpu: true,
    }),
    drift: num({
      min: -0.5,
      max: 0.5,
      step: 0.001,
      default: 0,
      label: 'Drift',
      description: 'Palette scrolling, in cycles per second.',
    }),
    saturation: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 1.05,
      label: 'Saturation',
      description: 'Saturation of the cell colors.',
      gpu: true,
    }),
    hot: group(
      {
        label: 'Hot core',
        description: 'The brightest cells turn lighter in a tint of their own color.',
      },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.15,
          label: 'Amount',
          description: 'How much the bright cells lighten.',
          gpu: true,
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.92,
          label: 'Threshold',
          description: 'Brightness at which the hot core starts.',
          gpu: true,
        }),
        core: num({
          min: 0.1,
          max: 1,
          step: 0.01,
          default: 0.8,
          label: 'Core',
          description: 'Size of the hot middle of a cell.',
          gpu: true,
        }),
      },
    ),
    accent: group(
      {
        label: 'Accent',
        description:
          'Organic patches of a second color on the inner edge of the sphere, only in the cool half of the palette (teal within blue).',
      },
      {
        color: color({
          default: '#12c0d8',
          label: 'Color',
          description: 'Color of the accent patches.',
          gpu: true,
        }),
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.9,
          label: 'Amount',
          description: 'How strongly the patches take the accent color; 0 turns it off.',
          gpu: true,
        }),
      },
    ),
  },
);

const spot = (
  label: string,
  c: string,
  position: [number, number],
  radius: number,
  strength: number,
) =>
  group(
    { label, description: 'A soft color spot on the background.' },
    {
      color: color({ default: c, label: 'Color', description: 'Spot color.', gpu: true }),
      position: vec2({
        min: -2,
        max: 2,
        step: 0.01,
        default: position,
        label: 'Position',
        description: 'Spot center in mode units.',
        gpu: true,
      }),
      radius: num({
        min: 0.1,
        max: 4,
        step: 0.01,
        default: radius,
        label: 'Radius',
        description: 'Spot size.',
        gpu: true,
      }),
      strength: num({
        min: 0,
        max: 1,
        step: 0.01,
        default: strength,
        label: 'Strength',
        description: 'Spot brightness.',
        gpu: true,
      }),
    },
  );

const background = group(
  {
    label: 'Background',
    order: 60,
    description: 'The backdrop under the grid: color, vignette and color spots.',
  },
  {
    color: color({
      default: '#000032',
      label: 'Color',
      description: 'Main background color.',
      gpu: true,
    }),
    vignette: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.35,
      label: 'Vignette',
      description: 'Darkens the background corners (the cells are not affected).',
      gpu: true,
    }),
    spotA: spot('Spot A', '#6a1f6e', [-1.3, -0.2], 1.25, 0.65),
    spotB: spot('Spot B', '#16207e', [-0.8, 1.1], 0.9, 0.5),
  },
);

const glow = group(
  {
    label: 'Glow',
    order: 70,
    description: 'Halo around the cells, bloom and atmospheric haze.',
  },
  {
    halo: group(
      { label: 'Halo', description: 'Dense glow in the gaps around the cells.' },
      {
        strength: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.5,
          label: 'Strength',
          description: 'Halo brightness.',
          gpu: true,
        }),
        radius: num({
          min: 0.02,
          max: 0.5,
          step: 0.01,
          unit: 'cells',
          default: 0.18,
          label: 'Radius',
          description: 'How far the halo reaches into the gap.',
          gpu: true,
        }),
      },
    ),
    bloom: group(
      { label: 'Bloom', description: 'Soft glow of the bright areas.' },
      {
        strength: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.8,
          label: 'Strength',
          description: 'Bloom brightness.',
          gpu: true,
        }),
        radius: num({
          min: 0.5,
          max: 3,
          step: 0.05,
          unit: 'cells',
          default: 1.3,
          label: 'Radius',
          description: 'Bloom blur width, in cells.',
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Threshold',
          description: 'Brightness at which a cell starts to glow.',
          gpu: true,
        }),
        knee: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.5,
          label: 'Threshold knee',
          description: 'Softness of the transition through the threshold.',
          gpu: true,
        }),
      },
    ),
    haze: group(
      { label: 'Haze', description: 'Wide atmospheric glow.' },
      {
        strength: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.12,
          label: 'Strength',
          description: 'Haze brightness.',
          gpu: true,
        }),
        radius: num({
          min: 2,
          max: 12,
          step: 0.1,
          unit: 'cells',
          default: 4,
          label: 'Radius',
          description: 'Haze blur width, in cells.',
        }),
      },
    ),
    saturation: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 1.15,
      label: 'Glow saturation',
      description: 'Saturation of the halo, bloom and haze.',
      gpu: true,
    }),
    exposure: num({
      min: 0.2,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Exposure',
      description: 'Overall brightness before tone mapping.',
      gpu: true,
    }),
    whitePoint: num({
      min: 1,
      max: 16,
      step: 0.1,
      default: 4,
      label: 'White point',
      description: 'Brightness that maps to white; higher values give softer highlights.',
      gpu: true,
    }),
  },
);

const whenFloat = { path: 'lift.style', eq: 'float' } as const;

const lift = group(
  {
    label: 'Lifted pixels',
    order: 80,
    description: 'Individual cells rise above the grid and settle back.',
  },
  {
    enabled: bool({
      default: true,
      label: 'Enabled',
      description: 'Show lifted pixels.',
    }),
    style: enumField({
      values: ['pop', 'float'] as const,
      default: 'pop',
      label: 'Style',
      description: 'Pop up in place or float upward like bubbles.',
      labels: { pop: 'Pop', float: 'Float' },
    }),
    amount: num({
      min: 0,
      max: 0.06,
      step: 0.001,
      default: 0.016,
      label: 'Amount',
      description: 'Share of cells lifted at the same time.',
    }),
    max: int({
      min: 0,
      max: 128,
      step: 1,
      default: 96,
      label: 'Maximum',
      description: 'Limit on simultaneously lifted cells.',
      live: 'static',
    }),
    scale: num({
      min: 1,
      max: 2.5,
      step: 0.01,
      default: 1.5,
      label: 'Scale',
      description: 'How many times larger a lifted cell is.',
    }),
    height: num({
      min: 0,
      max: 2,
      step: 0.01,
      unit: 'cells',
      default: 0.35,
      label: 'Height',
      description: 'Upward offset while lifted.',
    }),
    parallax: num({
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.06,
      label: 'Parallax',
      description: 'Offset away from the center that adds a sense of depth.',
    }),
    tilt: num({
      min: 0,
      max: 20,
      step: 0.5,
      unit: '°',
      default: 6,
      label: 'Tilt',
      description: 'Random tilt of a lifted cell.',
    }),
    holdMin: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 's',
      default: 1.5,
      label: 'Hold min',
      description: 'Minimum time spent lifted.',
    }),
    holdMax: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 's',
      default: 3.5,
      label: 'Hold max',
      description: 'Maximum time spent lifted.',
    }),
    rise: num({
      min: 0.1,
      max: 2,
      step: 0.01,
      unit: 's',
      default: 0.6,
      label: 'Rise',
      description: 'Rise duration (with a springy overshoot).',
    }),
    fall: num({
      min: 0.1,
      max: 2,
      step: 0.01,
      unit: 's',
      default: 0.45,
      label: 'Fall',
      description: 'Duration of the return to place.',
    }),
    brightness: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.9,
      label: 'Brightness',
      description: 'Extra brightness of a lifted cell.',
      gpu: true,
    }),
    whiten: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Whiten',
      description: 'Shifts the color toward a lighter tint.',
      gpu: true,
    }),
    bokeh: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.3,
      label: 'Bokeh',
      description: 'Share of lifted cells blurred as if out of focus.',
    }),
    shadow: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.4,
      label: 'Shadow',
      description: 'Density of the shadow under a lifted cell.',
      gpu: true,
    }),
    halo: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Halo',
      description: 'Glow around a lifted cell.',
      gpu: true,
    }),
    socket: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.6,
      label: 'Socket',
      description: 'How much the spot a cell rose from darkens.',
    }),
    threshold: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.2,
      label: 'Threshold',
      description: 'Minimum cell brightness required to lift.',
      gpu: true,
    }),
    outerBias: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.85,
      label: 'Edge bias',
      description: 'Prefer outer and dim areas.',
    }),
    cluster: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.15,
      label: 'Clusters',
      description: 'Chance to lift neighboring cells together with a cell.',
    }),
    landing: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.25,
      label: 'Landing',
      description: 'Strength of the ripple ring when a cell lands.',
    }),
    floatSpeed: num({
      min: 0.1,
      max: 4,
      step: 0.01,
      unit: 'cells/s',
      default: 0.9,
      label: 'Float speed',
      description: 'Rise speed in the Float style.',
      visibleWhen: whenFloat,
    }),
    floatDrift: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.4,
      label: 'Drift',
      description: 'Sideways sway while floating.',
      visibleWhen: whenFloat,
    }),
  },
);

const interaction = group(
  {
    label: 'Interaction',
    order: 90,
    description: 'Response to the pointer and clicks, and defaults for bound elements.',
  },
  {
    pointer: bool({
      default: false,
      label: 'Pointer',
      description: 'Light up the cells under the pointer.',
    }),
    pointerRadius: num({
      min: 1,
      max: 30,
      step: 0.5,
      unit: 'cells',
      default: 4,
      label: 'Pointer radius',
      description: 'Size of the light spot around the pointer.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    pointerStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.6,
      label: 'Pointer strength',
      description: 'Brightness of the highlight under the pointer.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    pointerLift: bool({
      default: true,
      label: 'Lift on hover',
      description: 'Lift cells under the pointer.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    click: bool({
      default: true,
      label: 'Click',
      description: 'Start a ripple on click.',
    }),
    rippleStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Ripple strength',
      description: 'Brightness of the click ripple.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    rippleSpeed: num({
      min: 2,
      max: 60,
      step: 0.5,
      unit: 'cells/s',
      default: 18,
      label: 'Ripple speed',
      description: 'How fast the ripple expands.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    rippleWidth: num({
      min: 0.5,
      max: 6,
      step: 0.1,
      unit: 'cells',
      default: 1.5,
      label: 'Ripple width',
      description: 'Thickness of the ripple ring.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    influenceStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Influence strength',
      description: 'Default strength for bound elements (bindElement / addInfluence).',
    }),
    influenceFalloff: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 'cells',
      default: 2,
      label: 'Influence falloff',
      description: 'Default width of the soft edge of an influence.',
    }),
  },
);

const render = group(
  {
    label: 'Performance',
    order: 100,
    advanced: true,
    description: 'Quality, resolution and frame rate.',
  },
  {
    quality: enumField({
      values: ['auto', 'high', 'medium', 'low'] as const,
      default: 'auto',
      label: 'Quality',
      description: '"Auto" lowers the quality when the device cannot keep up.',
      labels: { auto: 'Auto', high: 'High', medium: 'Medium', low: 'Low' },
      live: 'static',
    }),
    maxDpr: num({
      min: 0.5,
      max: 3,
      step: 0.05,
      default: 2,
      label: 'Max DPR',
      description: 'Upper limit of the canvas pixel density.',
      live: 'static',
    }),
    maxPixels: num({
      min: 0.3,
      max: 12,
      step: 0.1,
      unit: 'MP',
      default: 4.2,
      label: 'Max pixels',
      description: 'Upper limit of the canvas size; phones are capped at 2.4 MP.',
      live: 'static',
    }),
    overflow: num({
      min: 0,
      max: 300,
      step: 1,
      unit: 'px',
      default: 0,
      label: 'Overflow',
      description: 'The canvas extends past the container so the glow is not clipped.',
      live: 'static',
    }),
    maxFps: int({
      min: 0,
      max: 240,
      step: 1,
      default: 0,
      label: 'Max FPS',
      description: '0 follows the display rate; otherwise an integer divisor of the refresh rate.',
      live: 'static',
    }),
    pauseOffscreen: bool({
      default: true,
      label: 'Pause offscreen',
      description: 'Stop rendering while the background is not visible.',
      live: 'static',
    }),
    reducedMotion: enumField({
      values: ['respect', 'ignore'] as const,
      default: 'respect',
      label: 'Reduced motion',
      description: 'Whether to honor the system prefers-reduced-motion setting.',
      labels: { respect: 'Respect', ignore: 'Ignore' },
      live: 'static',
    }),
  },
);

const transition = num({
  min: 0,
  max: 5000,
  step: 10,
  unit: 'ms',
  default: 600,
  label: 'Transition',
  description: 'Duration of the smooth transition when settings change.',
  live: 'static',
});

/** Root of the schema tree. */
export const schema = group(
  { label: 'LumiCells' },
  {
    grid,
    scene,
    animation,
    modes,
    color: colorGroup,
    background,
    glow,
    lift,
    interaction,
    render,
    transition,
  },
);

export type Schema = typeof schema;
export type SchemaTree = Schema['fields'];

export const CONFIG_VERSION = 1 as const;

/** Mode ids in shader/stand order. */
export const MODE_IDS = [
  'flow',
  'sphere',
  'pulse',
  'wave',
  'ripple',
  'vortex',
  'life',
  'rain',
] as const;
export type ModeId = (typeof MODE_IDS)[number];

/** The complete, normalized config. */
export type LumiCellsConfig = { version: typeof CONFIG_VERSION } & InferConfig<SchemaTree>;

type ConfigBody = InferConfig<SchemaTree>;

/** What users write: any subset of the config, optionally based on a preset. */
export type LumiCellsConfigInput = DeepPartial<ConfigBody> & {
  $schema?: string;
  version?: number;
  extends?: PresetId;
};

/** Dotted path of every leaf parameter, e.g. 'glow.bloom.strength' | 'color.palette'. */
export type ParamPath = SchemaLeafPaths<SchemaTree>;

export type ParamValue<P extends ParamPath> = PathValue<ConfigBody, P>;

/** Schema field definition at a path. */
export type FieldAt<P extends ParamPath> = NodeAt<SchemaTree, P>;

/** Paths of numeric parameters: the ones that can be tweened and modulated. */
export type ModulatablePath = {
  [P in ParamPath]: ParamValue<P> extends number ? P : never;
}[ParamPath];
