/**
 * THE config schema tree. Everything else (types, defaults, normalization, stand UI, JSON Schema,
 * GPU layout) is derived from this object, so paths, ranges and defaults live only here.
 *
 * Defaults are the "reference" look. Units: "cells" = grid pitch units; "mode units" =
 * aspect-correct space where 1.0 = half of the host's shorter side.
 */

import {
  angle,
  bool,
  color,
  type DeepPartial,
  enumField,
  group,
  type InferConfig,
  int,
  type NodeAt,
  num,
  type PathValue,
  palette,
  type SchemaLeafPaths,
  vec2,
} from './fields';
import type { PresetId } from './presets';

const grid = group(
  {
    label: 'Сетка',
    order: 10,
    description: 'Размер и форма ячеек пиксельной сетки.',
  },
  {
    sizing: enumField({
      values: ['pitch', 'count'] as const,
      default: 'count',
      label: 'Размер ячейки',
      description:
        'Задавать сетку фиксированным шагом в пикселях или числом ячеек по короткой стороне контейнера.',
      labels: { pitch: 'Шаг в px', count: 'Число ячеек' },
      live: 'realloc',
    }),
    pitch: num({
      min: 4,
      max: 96,
      step: 1,
      unit: 'px',
      default: 24,
      label: 'Шаг',
      description: 'Расстояние между центрами соседних ячеек в CSS-пикселях.',
      live: 'realloc',
      visibleWhen: { path: 'grid.sizing', eq: 'pitch' },
    }),
    count: int({
      min: 8,
      max: 200,
      step: 1,
      default: 31,
      label: 'Ячеек',
      description:
        'Сколько ячеек помещается по короткой стороне контейнера. Композиция тогда выглядит одинаково в квадрате, баннере и на весь экран.',
      live: 'realloc',
      visibleWhen: { path: 'grid.sizing', eq: 'count' },
    }),
    gap: num({
      min: 0.02,
      max: 0.6,
      step: 0.01,
      default: 0.27,
      label: 'Зазор',
      description: 'Доля шага, занятая тёмным промежутком между ячейками.',
      gpu: true,
    }),
    roundness: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.3,
      label: 'Скругление',
      description: 'Радиус углов как доля половины ячейки: 0 — квадрат, 1 — круг.',
      gpu: true,
    }),
    softness: num({
      min: 0,
      max: 3,
      step: 0.05,
      unit: 'px',
      default: 0.6,
      label: 'Мягкость края',
      description: 'Растушёвка края ячейки в физических пикселях.',
      gpu: true,
    }),
    emitter: num({
      min: 0,
      max: 0.6,
      step: 0.01,
      default: 0.18,
      label: 'Излучатель',
      description: 'Насколько центр ячейки ярче её краёв.',
      gpu: true,
    }),
    bevel: num({
      min: 0,
      max: 0.15,
      step: 0.01,
      default: 0,
      label: 'Фаска',
      description: 'Лёгкий объём: светлая верхняя и тёмная нижняя грань ячейки.',
      gpu: true,
      advanced: true,
    }),
  },
);

const scene = group(
  {
    label: 'Композиция',
    order: 20,
    description: 'Положение и масштаб всей картины внутри контейнера.',
  },
  {
    center: vec2({
      min: -1,
      max: 1,
      step: 0.01,
      default: [-0.02, -0.02],
      label: 'Центр',
      description: 'Центр композиции в единицах режима (1 = половина меньшей стороны).',
      gpu: true,
    }),
    zoom: num({
      min: 0.25,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Масштаб',
      description: 'Увеличение всех режимов относительно центра.',
      gpu: true,
    }),
  },
);

const animation = group(
  {
    label: 'Анимация',
    order: 30,
    description: 'Общая скорость, смешивание режимов и живость ячеек.',
  },
  {
    speed: num({
      min: 0,
      max: 4,
      step: 0.01,
      default: 1,
      label: 'Скорость',
      description: 'Глобальный множитель времени для всех режимов.',
    }),
    blend: enumField({
      values: ['screen', 'add', 'max'] as const,
      default: 'screen',
      label: 'Смешивание режимов',
      description: 'Как складываются несколько активных режимов.',
      labels: { screen: 'Экран', add: 'Сложение', max: 'Максимум' },
      gpu: true,
    }),
    brightness: num({
      min: 0,
      max: 3,
      step: 0.01,
      default: 1,
      label: 'Яркость',
      description: 'Множитель интенсивности ячеек.',
      gpu: true,
    }),
    gamma: num({
      min: 0.3,
      max: 3,
      step: 0.01,
      default: 1.15,
      label: 'Контраст (гамма)',
      description: 'Больше единицы — темнее полутона и контрастнее картинка.',
      gpu: true,
    }),
    floor: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.16,
      label: 'Видимость погасших',
      description: 'Насколько заметны неосвещённые ячейки.',
      gpu: true,
    }),
    energy: num({
      min: 0,
      max: 3,
      step: 0.01,
      default: 1,
      label: 'Энергия',
      description: 'Внешний «драйв»: удобно модулировать звуком или событиями.',
      gpu: true,
    }),
    flicker: group(
      { label: 'Мерцание', description: 'Медленное случайное дыхание яркости каждой ячейки.' },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.4,
          label: 'Сила',
          description: 'Амплитуда мерцания.',
          gpu: true,
        }),
        rate: num({
          min: 0.05,
          max: 5,
          step: 0.01,
          unit: 'Гц',
          default: 0.3,
          label: 'Частота',
          description: 'Как быстро меняется яркость.',
          gpu: true,
        }),
      },
    ),
    sparkle: group(
      { label: 'Искры', description: 'Редкие короткие вспышки отдельных ячеек.' },
      {
        amount: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.35,
          label: 'Сила',
          description: 'Прибавка яркости во время вспышки.',
          gpu: true,
        }),
        rate: num({
          min: 0,
          max: 0.05,
          step: 0.001,
          default: 0.008,
          label: 'Частота',
          description: 'Вероятность вспышки на ячейку в секунду.',
          gpu: true,
        }),
        duration: num({
          min: 0.1,
          max: 2,
          step: 0.01,
          unit: 'с',
          default: 0.5,
          label: 'Длительность',
          description: 'Длина одной вспышки.',
          gpu: true,
        }),
      },
    ),
    sparsity: group(
      {
        label: 'Разреженность',
        description: 'На окраинах ячейки гаснут целиком, а не тускнеют.',
      },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.55,
          label: 'Сила',
          description: 'Доля погашенных ячеек в слабых областях.',
          gpu: true,
        }),
        period: num({
          min: 0.5,
          max: 10,
          step: 0.1,
          unit: 'с',
          default: 3,
          label: 'Период',
          description: 'Как часто перетасовываются погашенные ячейки.',
          gpu: true,
        }),
      },
    ),
  },
);

const weight = (value: number, label = 'Вес') =>
  num({
    min: 0,
    max: 1,
    step: 0.01,
    default: value,
    label,
    description: 'Вклад режима в итоговую картину; 0 — режим выключен.',
    gpu: true,
  });

const modes = group(
  {
    label: 'Режимы анимации',
    order: 40,
    description: 'Слои поля яркости; можно смешивать несколько режимов одновременно.',
  },
  {
    flow: group(
      { label: 'Поток', kind: 'mode', description: 'Плавно текущий шумовой узор.' },
      {
        weight: weight(0.1),
        scale: num({
          min: 0.2,
          max: 8,
          step: 0.01,
          scale: 'log',
          default: 1.6,
          label: 'Масштаб',
          description: 'Частота шумового узора: больше — мельче пятна.',
          gpu: true,
        }),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.25,
          label: 'Скорость',
          description: 'Скорость течения узора.',
        }),
        direction: angle({
          default: 30,
          label: 'Направление',
          description: 'Куда течёт узор.',
          gpu: true,
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.45,
          label: 'Порог',
          description: 'Выше — меньше светящихся пятен.',
          gpu: true,
        }),
        softness: num({
          min: 0.02,
          max: 1,
          step: 0.01,
          default: 0.3,
          label: 'Мягкость',
          description: 'Ширина перехода от тёмного к светлому.',
          gpu: true,
        }),
      },
    ),
    sphere: group(
      {
        label: 'Сфера',
        kind: 'mode',
        description: 'Светящийся полый шар с кольцом и мягким угасанием.',
      },
      {
        weight: weight(1),
        radius: num({
          min: 0.1,
          max: 1.6,
          step: 0.01,
          default: 0.68,
          label: 'Радиус',
          description: 'Радиус сферы в единицах режима.',
          gpu: true,
        }),
        shift: vec2({
          min: -1,
          max: 1,
          step: 0.01,
          default: [0.02, 0.16],
          label: 'Смещение оболочки',
          description:
            'Сдвиг светящейся оболочки относительно отверстия: с этой стороны кольцо толще и плотнее, отверстие остаётся в центре.',
          gpu: true,
        }),
        hole: num({
          min: 0,
          max: 0.9,
          step: 0.01,
          default: 0.25,
          label: 'Отверстие',
          description: 'Радиус тёмной середины; 0 — сплошной шар.',
          gpu: true,
        }),
        holeSoftness: num({
          min: 0.01,
          max: 0.5,
          step: 0.01,
          default: 0.12,
          label: 'Мягкость отверстия',
          description: 'Ширина перехода от отверстия к яркому кольцу.',
          gpu: true,
        }),
        rimPower: num({
          min: 0.3,
          max: 6,
          step: 0.01,
          default: 1.3,
          label: 'Ободок',
          description: 'Больше — свет сильнее прижат к краю сферы.',
          gpu: true,
        }),
        outerFalloff: num({
          min: 0.05,
          max: 1.5,
          step: 0.01,
          default: 0.38,
          label: 'Внешнее затухание',
          description: 'Как далеко свет уходит за радиус сферы.',
          gpu: true,
        }),
        lightAngle: angle({
          default: 200,
          label: 'Направление света',
          description: 'С какой стороны сфера освещена сильнее.',
          gpu: true,
        }),
        lightStrength: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.45,
          label: 'Сила света',
          description: 'Контраст между освещённой и теневой стороной.',
          gpu: true,
        }),
        rotationSpeed: num({
          min: -2,
          max: 2,
          step: 0.01,
          default: 0.12,
          label: 'Вращение',
          description: 'Скорость вращения поверхности сферы (знак — направление).',
        }),
        tilt: angle({
          min: -60,
          max: 60,
          default: 20,
          label: 'Наклон оси',
          description: 'Наклон оси вращения.',
          gpu: true,
        }),
        surface: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.55,
          label: 'Рельеф',
          description: 'Сила узора на поверхности сферы.',
          gpu: true,
        }),
        surfaceScale: num({
          min: 0.5,
          max: 8,
          step: 0.01,
          default: 2.5,
          label: 'Масштаб рельефа',
          description: 'Частота узора на поверхности.',
          gpu: true,
        }),
        wobble: num({
          min: 0,
          max: 0.3,
          step: 0.005,
          default: 0.08,
          label: 'Неровность',
          description: 'Искажение формы сферы шумом.',
          gpu: true,
        }),
        breathe: num({
          min: 0,
          max: 0.2,
          step: 0.005,
          default: 0.025,
          label: 'Дыхание',
          description: 'Амплитуда пульсации радиуса.',
          gpu: true,
        }),
        breatheSpeed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.35,
          label: 'Темп дыхания',
          description: 'Частота пульсации радиуса.',
        }),
        fadeAngle: angle({
          default: 345,
          label: 'Сторона угасания',
          description: 'Направление, в котором сфера растворяется в фоне.',
          gpu: true,
        }),
        fadeAmount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 1,
          label: 'Сила угасания',
          description: 'Насколько сильно гаснет сторона угасания.',
          gpu: true,
        }),
      },
    ),
    pulse: group(
      { label: 'Пульсация', kind: 'mode', description: 'Концентрические кольца от центра.' },
      {
        weight: weight(0),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.45,
          label: 'Скорость',
          description: 'Скорость расхождения колец.',
        }),
        frequency: num({
          min: 0.5,
          max: 12,
          step: 0.01,
          default: 3,
          label: 'Частота',
          description: 'Число колец на единицу режима.',
          gpu: true,
        }),
        width: num({
          min: 0.02,
          max: 0.6,
          step: 0.01,
          default: 0.14,
          label: 'Ширина',
          description: 'Толщина кольца.',
          gpu: true,
        }),
        breathe: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Дыхание',
          description: 'Общая пульсация яркости.',
          gpu: true,
        }),
        falloff: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 1,
          label: 'Затухание',
          description: 'Как быстро кольца гаснут с расстоянием.',
          gpu: true,
        }),
        origin: vec2({
          min: -1,
          max: 1,
          step: 0.01,
          default: [0, 0],
          label: 'Источник',
          description: 'Центр колец относительно центра композиции.',
          gpu: true,
        }),
      },
    ),
    wave: group(
      { label: 'Волны', kind: 'mode', description: 'Бегущие плоские волны с интерференцией.' },
      {
        weight: weight(0),
        angle: angle({
          default: 20,
          label: 'Направление',
          description: 'Направление распространения волн.',
          gpu: true,
        }),
        frequency: num({
          min: 0.2,
          max: 12,
          step: 0.01,
          default: 2.5,
          label: 'Частота',
          description: 'Число гребней на единицу режима.',
          gpu: true,
        }),
        speed: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.5,
          label: 'Скорость',
          description: 'Скорость бега волн.',
        }),
        sharpness: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Резкость',
          description: 'Больше — узкие яркие гребни.',
          gpu: true,
        }),
        interference: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.5,
          label: 'Интерференция',
          description: 'Примесь второй волны под другим углом.',
          gpu: true,
        }),
      },
    ),
    ripple: group(
      { label: 'Капли', kind: 'mode', description: 'Случайные круги, как от капель на воде.' },
      {
        weight: weight(0),
        rate: num({
          min: 0,
          max: 6,
          step: 0.01,
          unit: '/с',
          default: 1.2,
          label: 'Частота',
          description: 'Сколько капель появляется в секунду.',
          gpu: true,
        }),
        speed: num({
          min: 0.05,
          max: 2,
          step: 0.01,
          default: 0.4,
          label: 'Скорость',
          description: 'Скорость расхождения круга.',
          gpu: true,
        }),
        width: num({
          min: 0.02,
          max: 0.4,
          step: 0.01,
          default: 0.09,
          label: 'Ширина',
          description: 'Толщина круга.',
          gpu: true,
        }),
        life: num({
          min: 0.5,
          max: 6,
          step: 0.1,
          unit: 'с',
          default: 2.5,
          label: 'Время жизни',
          description: 'Сколько живёт один круг.',
          gpu: true,
        }),
      },
    ),
    vortex: group(
      { label: 'Вихрь', kind: 'mode', description: 'Закрученные спиральные рукава.' },
      {
        weight: weight(0),
        arms: int({
          min: 1,
          max: 8,
          step: 1,
          default: 3,
          label: 'Рукава',
          description: 'Количество спиральных рукавов.',
          gpu: true,
        }),
        twist: num({
          min: -10,
          max: 10,
          step: 0.1,
          default: 3,
          label: 'Закрутка',
          description: 'Насколько сильно закручены рукава (знак — направление).',
          gpu: true,
        }),
        speed: num({
          min: -3,
          max: 3,
          step: 0.01,
          default: 0.3,
          label: 'Скорость',
          description: 'Скорость вращения вихря.',
        }),
        falloff: num({
          min: 0,
          max: 3,
          step: 0.01,
          default: 0.9,
          label: 'Затухание',
          description: 'Как быстро вихрь гаснет от центра.',
          gpu: true,
        }),
        sharpness: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.4,
          label: 'Резкость',
          description: 'Чёткость границ рукавов.',
          gpu: true,
        }),
      },
    ),
    life: group(
      {
        label: 'Жизнь',
        kind: 'mode',
        description: 'Клеточный автомат в духе «Жизни» Конвея.',
      },
      {
        weight: weight(0),
        stepRate: num({
          min: 1,
          max: 30,
          step: 0.1,
          unit: 'Гц',
          default: 8,
          label: 'Шагов в секунду',
          description: 'Скорость эволюции автомата.',
        }),
        birthRate: num({
          min: 0,
          max: 0.05,
          step: 0.0005,
          default: 0.004,
          label: 'Спонтанные рождения',
          description: 'Вероятность случайного рождения клетки за шаг — не даёт полю вымереть.',
        }),
        fadeSteps: int({
          min: 1,
          max: 16,
          step: 1,
          default: 4,
          label: 'Затухание',
          description: 'Сколько шагов гаснет умершая клетка.',
          gpu: true,
        }),
        seedDensity: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.3,
          label: 'Плотность посева',
          description: 'Доля живых клеток после сброса.',
        }),
        rule: enumField({
          values: ['conway', 'highlife', 'daynight', 'seeds'] as const,
          default: 'conway',
          label: 'Правило',
          description: 'Правило рождения и выживания; смена правила перезапускает поле.',
          labels: {
            conway: 'Конвей B3/S23',
            highlife: 'HighLife B36/S23',
            daynight: 'День и ночь',
            seeds: 'Семена B2/S',
          },
          live: 'restart',
        }),
      },
    ),
    rain: group(
      { label: 'Дождь', kind: 'mode', description: 'Падающие светящиеся капли со шлейфом.' },
      {
        weight: weight(0),
        speed: num({
          min: 0.1,
          max: 5,
          step: 0.01,
          default: 1,
          label: 'Скорость',
          description: 'Скорость падения капель.',
        }),
        density: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.25,
          label: 'Плотность',
          description: 'Доля колонок, по которым идёт дождь.',
          gpu: true,
        }),
        tail: num({
          min: 0.05,
          max: 1.5,
          step: 0.01,
          default: 0.5,
          label: 'Шлейф',
          description: 'Длина светящегося следа за каплей.',
          gpu: true,
        }),
        angle: angle({
          min: -45,
          max: 45,
          default: 0,
          label: 'Наклон',
          description: 'Отклонение дождя от вертикали.',
          gpu: true,
        }),
      },
    ),
  },
);

const colorGroup = group(
  {
    label: 'Цвет',
    order: 50,
    description: 'Палитра и то, как она ложится на сетку.',
  },
  {
    palette: palette({
      default: [
        '#a0206a',
        '#f21239',
        '#e0267a',
        '#5a44d0',
        '#2a55e0',
        '#1f5fe8',
        '#0870f8',
        '#0476ff',
        '#0a84f2',
        '#0a8cf0',
        '#0a78e8',
        '#0b5ccc',
      ],
      minStops: 1,
      maxStops: 32,
      label: 'Палитра',
      description: 'Опорные цвета градиента от начала к концу.',
    }),
    interpolation: enumField({
      values: ['oklab', 'linear', 'steps'] as const,
      default: 'oklab',
      label: 'Интерполяция',
      description: 'Как смешиваются соседние цвета палитры.',
      labels: { oklab: 'OKLab (ровно)', linear: 'Линейно (RGB)', steps: 'Ступени' },
      live: 'lut',
    }),
    mapping: enumField({
      values: ['spatial', 'radial', 'angular', 'intensity', 'noise'] as const,
      default: 'spatial',
      label: 'Раскладка',
      description: 'Что определяет место ячейки на палитре.',
      labels: {
        spatial: 'По оси',
        radial: 'По радиусу',
        angular: 'По углу',
        intensity: 'По яркости',
        noise: 'Шум',
      },
      transition: 'crossfade',
      gpu: true,
    }),
    angle: angle({
      default: 22,
      label: 'Угол оси',
      description: 'Направление от начала палитры к концу (для раскладки по оси).',
      gpu: true,
    }),
    bend: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0.35,
      label: 'Изгиб оси',
      description:
        'Выгибает границы цветов дугой вокруг центра (для раскладки по оси): начальный цвет собирается в серп с одной стороны.',
      gpu: true,
    }),
    scale: num({
      min: 0.1,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Растяжение',
      description: 'Больше — палитра повторяется чаще.',
      gpu: true,
    }),
    offset: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0,
      label: 'Сдвиг',
      description: 'Смещение палитры вдоль раскладки.',
      gpu: true,
    }),
    warp: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Искажение',
      description: 'Шумовое искривление границ цветов.',
      gpu: true,
    }),
    warpScale: num({
      min: 0.2,
      max: 6,
      step: 0.01,
      default: 1.3,
      label: 'Масштаб искажения',
      description: 'Частота шума искажения.',
      gpu: true,
    }),
    jitter: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.12,
      label: 'Разброс',
      description: 'Случайный сдвиг цвета каждой ячейки.',
      gpu: true,
    }),
    intensityShift: num({
      min: -1,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Сдвиг от яркости',
      description: 'Яркие ячейки смещаются по палитре.',
      gpu: true,
    }),
    drift: num({
      min: -0.5,
      max: 0.5,
      step: 0.001,
      default: 0,
      label: 'Дрейф',
      description: 'Прокрутка палитры, циклов в секунду.',
    }),
    saturation: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 1.05,
      label: 'Насыщенность',
      description: 'Насыщенность цвета ячеек.',
      gpu: true,
    }),
    hot: group(
      { label: 'Раскал', description: 'Самые яркие ячейки светлеют в оттенке своего цвета.' },
      {
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.15,
          label: 'Сила',
          description: 'Насколько сильно светлеют яркие ячейки.',
          gpu: true,
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.92,
          label: 'Порог',
          description: 'С какой яркости начинается раскал.',
          gpu: true,
        }),
        core: num({
          min: 0.1,
          max: 1,
          step: 0.01,
          default: 0.8,
          label: 'Ядро',
          description: 'Размер раскалённой середины ячейки.',
          gpu: true,
        }),
      },
    ),
    accent: group(
      {
        label: 'Акцент',
        description:
          'Органичные пятна второго цвета на внутренней кромке сферы — только в холодной половине палитры (бирюза в синем).',
      },
      {
        color: color({
          default: '#12c0d8',
          label: 'Цвет',
          description: 'Цвет акцентных пятен.',
          gpu: true,
        }),
        amount: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.9,
          label: 'Сила',
          description: 'Насколько пятна окрашиваются в цвет акцента; 0 — выключено.',
          gpu: true,
        }),
      },
    ),
  },
);

const spot = (
  label: string,
  c: string,
  position: [number, number],
  radius: number,
  strength: number,
) =>
  group(
    { label, description: 'Мягкое цветное пятно на фоне.' },
    {
      color: color({ default: c, label: 'Цвет', description: 'Цвет пятна.', gpu: true }),
      position: vec2({
        min: -2,
        max: 2,
        step: 0.01,
        default: position,
        label: 'Положение',
        description: 'Центр пятна в единицах режима.',
        gpu: true,
      }),
      radius: num({
        min: 0.1,
        max: 4,
        step: 0.01,
        default: radius,
        label: 'Радиус',
        description: 'Размер пятна.',
        gpu: true,
      }),
      strength: num({
        min: 0,
        max: 1,
        step: 0.01,
        default: strength,
        label: 'Сила',
        description: 'Яркость пятна.',
        gpu: true,
      }),
    },
  );

const background = group(
  {
    label: 'Фон',
    order: 60,
    description: 'Подложка под сеткой: цвет, виньетка и цветные пятна.',
  },
  {
    color: color({
      default: '#000032',
      label: 'Цвет',
      description: 'Основной цвет фона.',
      gpu: true,
    }),
    vignette: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.35,
      label: 'Виньетка',
      description: 'Затемнение углов фона (ячейки не затрагивает).',
      gpu: true,
    }),
    spotA: spot('Пятно A', '#6a1f6e', [-1.3, -0.2], 1.25, 0.65),
    spotB: spot('Пятно B', '#16207e', [-0.8, 1.1], 0.9, 0.5),
  },
);

const glow = group(
  {
    label: 'Свечение',
    order: 70,
    description: 'Ореол вокруг ячеек, блум и атмосферная дымка.',
  },
  {
    halo: group(
      { label: 'Ореол', description: 'Плотное свечение в зазорах вокруг ячеек.' },
      {
        strength: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.5,
          label: 'Сила',
          description: 'Яркость ореола.',
          gpu: true,
        }),
        radius: num({
          min: 0.02,
          max: 0.5,
          step: 0.01,
          unit: 'cells',
          default: 0.18,
          label: 'Радиус',
          description: 'Как далеко ореол заходит в зазор.',
          gpu: true,
        }),
      },
    ),
    bloom: group(
      { label: 'Блум', description: 'Мягкое свечение ярких областей.' },
      {
        strength: num({
          min: 0,
          max: 2,
          step: 0.01,
          default: 0.8,
          label: 'Сила',
          description: 'Яркость блума.',
          gpu: true,
        }),
        radius: num({
          min: 0.5,
          max: 3,
          step: 0.05,
          unit: 'cells',
          default: 1.3,
          label: 'Радиус',
          description: 'Ширина размытия блума в ячейках.',
        }),
        threshold: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.35,
          label: 'Порог',
          description: 'С какой яркости ячейка начинает светиться.',
          gpu: true,
        }),
        knee: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.5,
          label: 'Плавность порога',
          description: 'Мягкость перехода через порог.',
          gpu: true,
        }),
      },
    ),
    haze: group(
      { label: 'Дымка', description: 'Широкое атмосферное свечение.' },
      {
        strength: num({
          min: 0,
          max: 1,
          step: 0.01,
          default: 0.12,
          label: 'Сила',
          description: 'Яркость дымки.',
          gpu: true,
        }),
        radius: num({
          min: 2,
          max: 12,
          step: 0.1,
          unit: 'cells',
          default: 4,
          label: 'Радиус',
          description: 'Ширина размытия дымки в ячейках.',
        }),
      },
    ),
    saturation: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 1.15,
      label: 'Насыщенность свечения',
      description: 'Насыщенность ореола, блума и дымки.',
      gpu: true,
    }),
    exposure: num({
      min: 0.2,
      max: 4,
      step: 0.01,
      scale: 'log',
      default: 1,
      label: 'Экспозиция',
      description: 'Общая яркость перед тонмаппингом.',
      gpu: true,
    }),
    whitePoint: num({
      min: 1,
      max: 16,
      step: 0.1,
      default: 4,
      label: 'Точка белого',
      description: 'Какая яркость становится белой; больше — мягче пересветы.',
      gpu: true,
    }),
  },
);

const whenFloat = { path: 'lift.style', eq: 'float' } as const;

const lift = group(
  {
    label: 'Всплывающие пиксели',
    order: 80,
    description: 'Отдельные ячейки приподнимаются над сеткой и опускаются обратно.',
  },
  {
    enabled: bool({
      default: true,
      label: 'Включено',
      description: 'Показывать всплывающие пиксели.',
    }),
    style: enumField({
      values: ['pop', 'float'] as const,
      default: 'pop',
      label: 'Стиль',
      description: 'Подъём на месте или всплытие вверх, как пузырьки.',
      labels: { pop: 'Подъём', float: 'Всплытие' },
    }),
    amount: num({
      min: 0,
      max: 0.06,
      step: 0.001,
      default: 0.016,
      label: 'Количество',
      description: 'Доля ячеек, поднятых одновременно.',
    }),
    max: int({
      min: 0,
      max: 128,
      step: 1,
      default: 96,
      label: 'Максимум',
      description: 'Предел одновременно поднятых ячеек.',
      live: 'static',
    }),
    scale: num({
      min: 1,
      max: 2.5,
      step: 0.01,
      default: 1.5,
      label: 'Увеличение',
      description: 'Во сколько раз поднятая ячейка больше обычной.',
    }),
    height: num({
      min: 0,
      max: 2,
      step: 0.01,
      unit: 'cells',
      default: 0.35,
      label: 'Высота',
      description: 'Смещение вверх при подъёме.',
    }),
    parallax: num({
      min: 0,
      max: 0.3,
      step: 0.01,
      default: 0.06,
      label: 'Параллакс',
      description: 'Сдвиг от центра, создающий ощущение глубины.',
    }),
    tilt: num({
      min: 0,
      max: 20,
      step: 0.5,
      unit: '°',
      default: 6,
      label: 'Наклон',
      description: 'Случайный наклон поднятой ячейки.',
    }),
    holdMin: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 'с',
      default: 1.5,
      label: 'Удержание от',
      description: 'Минимальное время в поднятом состоянии.',
    }),
    holdMax: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 'с',
      default: 3.5,
      label: 'Удержание до',
      description: 'Максимальное время в поднятом состоянии.',
    }),
    rise: num({
      min: 0.1,
      max: 2,
      step: 0.01,
      unit: 'с',
      default: 0.6,
      label: 'Подъём',
      description: 'Длительность подъёма (с пружинным отскоком).',
    }),
    fall: num({
      min: 0.1,
      max: 2,
      step: 0.01,
      unit: 'с',
      default: 0.45,
      label: 'Опускание',
      description: 'Длительность возвращения на место.',
    }),
    brightness: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.9,
      label: 'Яркость',
      description: 'Дополнительная яркость поднятой ячейки.',
      gpu: true,
    }),
    whiten: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.12,
      label: 'Высветление',
      description: 'Сдвиг цвета к светлому оттенку.',
      gpu: true,
    }),
    bokeh: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.3,
      label: 'Боке',
      description: 'Доля поднятых ячеек, размытых как вне фокуса.',
    }),
    shadow: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.4,
      label: 'Тень',
      description: 'Плотность тени под поднятой ячейкой.',
      gpu: true,
    }),
    halo: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Ореол',
      description: 'Свечение вокруг поднятой ячейки.',
      gpu: true,
    }),
    socket: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.6,
      label: 'Гнездо',
      description: 'Насколько темнеет место, откуда поднялась ячейка.',
    }),
    threshold: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.2,
      label: 'Порог',
      description: 'Минимальная яркость ячейки, чтобы она могла подняться.',
      gpu: true,
    }),
    outerBias: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.85,
      label: 'Тяга к краю',
      description: 'Предпочитать внешние и тусклые области.',
    }),
    cluster: num({
      min: 0,
      max: 0.5,
      step: 0.01,
      default: 0.15,
      label: 'Группы',
      description: 'Вероятность поднять вместе с ячейкой её соседей.',
    }),
    landing: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.25,
      label: 'Приземление',
      description: 'Сила кольца-волны при опускании.',
    }),
    floatSpeed: num({
      min: 0.1,
      max: 4,
      step: 0.01,
      unit: 'cells/с',
      default: 0.9,
      label: 'Скорость всплытия',
      description: 'Скорость подъёма в стиле «Всплытие».',
      visibleWhen: whenFloat,
    }),
    floatDrift: num({
      min: 0,
      max: 1,
      step: 0.01,
      default: 0.4,
      label: 'Снос',
      description: 'Боковое покачивание при всплытии.',
      visibleWhen: whenFloat,
    }),
  },
);

const interaction = group(
  {
    label: 'Интерактив',
    order: 90,
    description: 'Реакция на курсор и клики, параметры привязки элементов.',
  },
  {
    pointer: bool({
      default: false,
      label: 'Курсор',
      description: 'Подсвечивать ячейки под курсором.',
    }),
    pointerRadius: num({
      min: 1,
      max: 30,
      step: 0.5,
      unit: 'cells',
      default: 4,
      label: 'Радиус курсора',
      description: 'Размер пятна света вокруг курсора.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    pointerStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.6,
      label: 'Сила курсора',
      description: 'Яркость подсветки под курсором.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    pointerLift: bool({
      default: true,
      label: 'Подъём под курсором',
      description: 'Поднимать ячейки при наведении.',
      visibleWhen: { path: 'interaction.pointer', eq: true },
    }),
    click: bool({
      default: true,
      label: 'Клик',
      description: 'Запускать волну по клику.',
    }),
    rippleStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Сила волны',
      description: 'Яркость волны от клика.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    rippleSpeed: num({
      min: 2,
      max: 60,
      step: 0.5,
      unit: 'cells/с',
      default: 18,
      label: 'Скорость волны',
      description: 'Скорость расхождения волны.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    rippleWidth: num({
      min: 0.5,
      max: 6,
      step: 0.1,
      unit: 'cells',
      default: 1.5,
      label: 'Ширина волны',
      description: 'Толщина кольца волны.',
      visibleWhen: { path: 'interaction.click', eq: true },
    }),
    influenceStrength: num({
      min: 0,
      max: 2,
      step: 0.01,
      default: 0.8,
      label: 'Сила влияний',
      description: 'Сила по умолчанию для привязанных элементов (bindElement / addInfluence).',
    }),
    influenceFalloff: num({
      min: 0.2,
      max: 10,
      step: 0.1,
      unit: 'cells',
      default: 2,
      label: 'Спад влияний',
      description: 'Ширина мягкого края влияния по умолчанию.',
    }),
  },
);

const render = group(
  {
    label: 'Производительность',
    order: 100,
    advanced: true,
    description: 'Качество, разрешение и частота кадров.',
  },
  {
    quality: enumField({
      values: ['auto', 'high', 'medium', 'low'] as const,
      default: 'auto',
      label: 'Качество',
      description: '«Авто» снижает качество, если устройство не успевает.',
      labels: { auto: 'Авто', high: 'Высокое', medium: 'Среднее', low: 'Низкое' },
      live: 'static',
    }),
    maxDpr: num({
      min: 0.5,
      max: 3,
      step: 0.05,
      default: 2,
      label: 'Макс. DPR',
      description: 'Предел плотности пикселей холста.',
      live: 'static',
    }),
    maxPixels: num({
      min: 0.3,
      max: 12,
      step: 0.1,
      unit: 'Мпикс',
      default: 4.2,
      label: 'Макс. пикселей',
      description: 'Предел размера холста; на телефонах не больше 2.4 Мпикс.',
      live: 'static',
    }),
    overflow: num({
      min: 0,
      max: 300,
      step: 1,
      unit: 'px',
      default: 0,
      label: 'Выход за край',
      description: 'Холст выходит за контейнер, чтобы свечение не обрезалось.',
      live: 'static',
    }),
    maxFps: int({
      min: 0,
      max: 240,
      step: 1,
      default: 0,
      label: 'Макс. FPS',
      description: '0 — частота дисплея; иначе целый делитель частоты обновления.',
      live: 'static',
    }),
    pauseOffscreen: bool({
      default: true,
      label: 'Пауза вне экрана',
      description: 'Останавливать отрисовку, когда фон не виден.',
      live: 'static',
    }),
    reducedMotion: enumField({
      values: ['respect', 'ignore'] as const,
      default: 'respect',
      label: 'Меньше движения',
      description: 'Учитывать системную настройку prefers-reduced-motion.',
      labels: { respect: 'Учитывать', ignore: 'Игнорировать' },
      live: 'static',
    }),
  },
);

const transition = num({
  min: 0,
  max: 5000,
  step: 10,
  unit: 'мс',
  default: 600,
  label: 'Переход',
  description: 'Длительность плавного перехода при смене настроек.',
  live: 'static',
});

/** Root of the schema tree. */
export const schema = group(
  { label: 'Pixel Life' },
  {
    grid,
    scene,
    animation,
    modes,
    color: colorGroup,
    background,
    glow,
    lift,
    interaction,
    render,
    transition,
  },
);

export type Schema = typeof schema;
export type SchemaTree = Schema['fields'];

export const CONFIG_VERSION = 1 as const;

/** Mode ids in shader/stand order. */
export const MODE_IDS = [
  'flow',
  'sphere',
  'pulse',
  'wave',
  'ripple',
  'vortex',
  'life',
  'rain',
] as const;
export type ModeId = (typeof MODE_IDS)[number];

/** The complete, normalized config. */
export type PixelLifeConfig = { version: typeof CONFIG_VERSION } & InferConfig<SchemaTree>;

type ConfigBody = InferConfig<SchemaTree>;

/** What users write: any subset of the config, optionally based on a preset. */
export type PixelLifeConfigInput = DeepPartial<ConfigBody> & {
  $schema?: string;
  version?: number;
  extends?: PresetId;
};

/** Dotted path of every leaf parameter, e.g. 'glow.bloom.strength' | 'color.palette'. */
export type ParamPath = SchemaLeafPaths<SchemaTree>;

export type ParamValue<P extends ParamPath> = PathValue<ConfigBody, P>;

/** Schema field definition at a path. */
export type FieldAt<P extends ParamPath> = NodeAt<SchemaTree, P>;

/** Paths of numeric parameters: the ones that can be tweened and modulated. */
export type ModulatablePath = {
  [P in ParamPath]: ParamValue<P> extends number ? P : never;
}[ParamPath];
